### ISSUE TITLE
Small caps not working on Safari, working on Firefox

### ISSUE THREAD

**Issue by jsilvela** [Mark2Mark/gintronic#5]
Tested on Safari 14.0.2 on macOS Big Sur 11.1 (i.e. latest releases of both)
And on the current Safari running on an up-to-date iPad.
Using the woff files.
With `font-variant: small-caps;` set in the CSS.
The numbers and capitals are rendering properly, the small caps are smaller than they should in proportion.
Looking fine on FireFox.

**Comment by jsilvela** [comment]
Also, Chrome seems to have problems with the lower caps. They seem smaller and thinner than they should.

**Comment by Mark2Mark** [comment]
Hi there. Thanks a lot, but I am not aware to have drawn any small caps for Gintronic. Could it be that Firefox ist just convincingly good at rendering fake small caps?

**Comment by jsilvela** [comment]
Oh, hahaha, that would explain that. With other fonts, the browsers didn't even try to render small caps. Just normal lower case letters. Since they tried with Gintronic, I jumped to conclusions.
Thank you.

**Comment by Mark2Mark** [comment]
Nevermind, thanks for the hint though 🙂  Hope you like it nevertheless.

**Comment by jsilvela** [comment]
Love it!
