### ISSUE TITLE
Angle brackets offset vertically on bbox site

### ISSUE THREAD

**Issue by gvolk0** [Mark2Mark/gintronic#6]
Just an FYI I saw this when playing with your font on the bbox site.  It happens with all font weights.  However I do **not** see this issue when using (the trial version of) your font in my terminal.  I get the same result in Firefox and Chrome.

![2021-03-05_111615](https://user-images.githubusercontent.com/8690075/110048843-bfbee780-7da4-11eb-9522-e11e2cd73784.jpg)

**Comment by Mark2Mark** [comment]
I think that might be due to an older version of the webfont that's used on the site. I might have fixed it in the shipping fonts, that's why it hopefully looks okay there. Thanks for reporting. Please let me know if you see that ir anything else in the "actual" fonts.

**Comment by Mark2Mark** [comment]
Resolved. Gintronic is now available through my own site, and this issue was fixed in the font a while ago
