### ISSUE TITLE
Website problem

### ISSUE THREAD

**Issue by astrolemonade** [Mark2Mark/gintronic#9]
Hello!
The font's website is not working anymore.
https://markfromberg.com/projects/gintronic/
![image](https://user-images.githubusercontent.com/35623921/171299278-53c006b4-a3e1-4a85-967f-87b102c9df29.png)
![image](https://user-images.githubusercontent.com/35623921/171299304-80c65a73-f27f-4930-950b-0d33ecea899c.png)

Can you look into it please?
Thank you for creating the font.

**Comment by Mark2Mark** [comment]
Thanks a lot for letting me know @cmarincia 

This is a really silly bug that I cannot get solved other than rebuilding the entire backend of the site (which I have no time for).

Fixed it with a stupid patchy patch now. Have to rename all folders once and rename them back, everytime after I push files to the ftp.

Should be running again. Thanks so much!

May I ask you how you found the font?

All best, Mark

**Comment by cmarincia** [comment]
I found it via multiple sources:
https://bboxtype.com/typefaces/Gintronic/#!layout=specimen
https://www.programmingfonts.org/#gintronic
https://atom.io/packages/kite (this was working at some point)
If you remember me, I am the one that suggested creating a repository for the font 😄 
I really like how the font works in my editors and I would be so happy if you would continue working on it. There is a lot of work to do, the font has so much potential.

**Comment by Mark2Mark** [comment]
ported my website to a new system, so this should not occur anymore
